version: '3.8'

services:
  proxy-convert:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: proxy-convert-go
    ports:
      - "5000:5000"
    volumes:
      - ./database:/root/database
      - ./templates:/root/templates
    environment:
      - SERVER_ADDR=0.0.0.0:5000
      - DATABASE_PATH=/root/database/links.db
    restart: unless-stopped
